// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyQseLQlkk6GR1SxlrNkAiMe1cgD14okk',
    appId: '1:1057552595575:web:ad278537a94a6f780e6472',
    messagingSenderId: '1057552595575',
    projectId: 'salonbelleza-21a78',
    authDomain: 'salonbelleza-21a78.firebaseapp.com',
    databaseURL: 'https://salonbelleza-21a78-default-rtdb.firebaseio.com',
    storageBucket: 'salonbelleza-21a78.appspot.com',
    measurementId: 'G-XJD9RESXY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_OvslhXXDG_fpc3_QJQUQzCa7yD-NQDA',
    appId: '1:1057552595575:android:8b0fac1ad2e44e1a0e6472',
    messagingSenderId: '1057552595575',
    projectId: 'salonbelleza-21a78',
    databaseURL: 'https://salonbelleza-21a78-default-rtdb.firebaseio.com',
    storageBucket: 'salonbelleza-21a78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0qj9K_MAWAWeoIacpxNXePZfMSBD6REM',
    appId: '1:1057552595575:ios:5ffbf869972053c20e6472',
    messagingSenderId: '1057552595575',
    projectId: 'salonbelleza-21a78',
    databaseURL: 'https://salonbelleza-21a78-default-rtdb.firebaseio.com',
    storageBucket: 'salonbelleza-21a78.appspot.com',
    iosBundleId: 'com.example.shopAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0qj9K_MAWAWeoIacpxNXePZfMSBD6REM',
    appId: '1:1057552595575:ios:5ffbf869972053c20e6472',
    messagingSenderId: '1057552595575',
    projectId: 'salonbelleza-21a78',
    databaseURL: 'https://salonbelleza-21a78-default-rtdb.firebaseio.com',
    storageBucket: 'salonbelleza-21a78.appspot.com',
    iosBundleId: 'com.example.shopAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyQseLQlkk6GR1SxlrNkAiMe1cgD14okk',
    appId: '1:1057552595575:web:b20dc14c875e113a0e6472',
    messagingSenderId: '1057552595575',
    projectId: 'salonbelleza-21a78',
    authDomain: 'salonbelleza-21a78.firebaseapp.com',
    databaseURL: 'https://salonbelleza-21a78-default-rtdb.firebaseio.com',
    storageBucket: 'salonbelleza-21a78.appspot.com',
    measurementId: 'G-45E69LVQN8',
  );
}
